console.log("Script Load");
(function($) {
    $(document).ready(function() {
        console.log('jQuery Ready');
        var $_0 = $('li._0'),
         $_1 = $('li._1'),
         $_2 = $('li._2'),
         $_3 = $('li._3'),
         $_4 = $('li._4'),
         $_5 = $('li._5'),
         $_6 = $('li._6'),
         $_7 = $('li._7'),
         $_8 = $('li._8'),
         $_9 = $('li._9'),
         $_10 = $('li._10');
         $_11 = $('li._11');

        $_0.on('click',function(){
            console.log('클릭했수다');
            $_0.css('transform', 'translateY(-2vw)');
            $_0.css('transition-delay', '0.8s');
            $_1.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_1.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/MemoriesOfMatsuko.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/NightPicnic.html">');
        });
        $_1.on('click',function(){
            console.log('클릭했수다');
            $_1.css('transform', 'translateY(-20px)');
            $_1.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/MemoriesOfMatsuko.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/MemoriesOfMatsuko.html">');
        });
        $_2.on('click',function(){
            console.log('클릭했수다2');
            $_2.css('transform', 'translateY(-7.7vw)');
            $_2.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_1.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/Moonassi.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Moonassi.html">');
        });
        $_3.on('click',function(){
            console.log('클릭했수다');
            $_3.css('transform', 'translateY(-120px)');
            $_3.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_1.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/Takkoyakki.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Takkoyakki.html">');
        });
        $_4.on('click',function(){
            console.log('클릭했수다');
            $_4.css('transform', 'translateY(-200px)');
            $_4.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/WhatYum.html">');
        });
        $_5.on('click',function(){
            console.log('클릭했수다');
            $_5.css('transform', 'translateY(-10.7vw)');
            $_5.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/NightOff.html">');
        });
        $_6.on('click',function(){
            console.log('클릭했수다');
            $_6.css('transform', 'translateY(-4.7vw)');
            $_6.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Momentrip.html">');
        });
        $_7.on('click',function(){
            console.log('클릭했수다');
            $_7.css('transform', 'translateY(-260px)');
            $_7.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_8.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Stalker.html">');
        });
        $_8.on('click',function(){
            console.log('클릭했수다');
            $_8.css('transform', 'translateY(10vw)');
            $_8.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_9.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/jinnykim.html">');
        });
        $_9.on('click',function(){
            console.log('클릭했수다');
            $_9.css('transform', 'translateY(7.4vw)');
            $_9.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_8.css('opacity', '0');
            $_10.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Tasty9.html">');
        });
        $_10.on('click',function(){
            console.log('클릭했수다');
            $_10.css('transform', 'translateY(1.7vw)');
            $_10.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_9.css('opacity', '0');
            $_8.css('opacity', '0');
            $_11.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_11.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Shopify.html">');
        });
        $_11.on('click',function(){
            console.log('클릭했수다');
            $_11.css('transform', 'translateY(5.1vw)');
            $_11.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            $_9.css('opacity', '0');
            $_8.css('opacity', '0');
            $_10.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                $_9.css('transform', 'translateX(10000px)');
                $_8.css('transform', 'translateX(10000px)');
                $_10.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/DebbyUpper.html">');
        });
    });
})(jQuery);